### PR TITLE
Replace navigate_existing_client with existing-client-retain

### PR DESCRIPTION
**Pull request by alancutter**
As suggested in: https://github.com/WICG/sw-launch/issues/45

### CODE REVIEW

**Comment by tomayac** [comment]
Reflected these changes in https://github.com/GoogleChrome/web.dev/pull/7434. It's a change for the better.

**Comment by alancutter** [comment]
Swapping reviewer to @fallaciousreasoning as @ericwilligers is OOO.

**Review by fallaciousreasoning — APPROVED** [review]
I'm a little out of the loop but this LGTM! Thanks @alancutter!

**Comment by alancutter** [comment]
Thanks!

**Pull request merged**
